### ISSUE TITLE
Auto-Restart

### ISSUE THREAD

**Issue by Pierce01** [EJH2/ViralBot#1]
try:
    loop.run_until_complete(bot.login("token"))
    loop.run_until_complete(bot.connect())
except Exception:
    loop.run_until_complete(os.system(""))
finally:
    loop.close()

**Comment by EJH2** [comment]
Fixed, thank you.

**Comment by Pierce01** [comment]
Forgot one thing.

`loop = asyncio.get_event_loop()`

Put that ontop so it looks like this.

loop = asyncio.get_event_loop()

try:
loop.run_until_complete(bot.login("token"))
loop.run_until_complete(bot.connect())
except Exception:
loop.run_until_complete(os.system(""))
finally:
loop.close()`
