### ISSUE TITLE
Feature Request: Add ^blacklist command

### ISSUE THREAD

**Issue by xPathin** [EJH2/ViralBot#3]
We once had a case in our discord where a user used a cancer name we changed over and over again and he always changed it back.
A ^blacklist command for the bot would be awesome. 
Maybe in this format: ^blacklist {word/nickname} action {rename/prune/kick/ban}

**Comment by EJH2** [comment]
Soon:tm:

**Comment by robingall2910** [comment]
It's been four months™

**Comment by Maxie01** [comment]
its been a year :lenny:

![image](https://cloud.githubusercontent.com/assets/18330673/22222884/af08cc1c-e186-11e6-82e5-6a70ff0e2e46.png)

**Comment by EJH2** [comment]
I've rolled out an early version of a Dynamic Rules framework, which will make this possible. It's in the works!
