### ISSUE TITLE
Add more embeds

### ISSUE THREAD

**Issue by robingall2910** [EJH2/ViralBot#5]
ADD MORE EMBEDS

**Comment by EJH2** [comment]
Working on it, bumping thread to remind self.

**Comment by ghost** [comment]
we dont need more embeds, regular text is just fine my dude

`
As many of you know, Discord recently implemented explicit content filtering for images. Whenever an image is uploaded, embeds via link, or is included in the image/author icon/footer icon/thumbnail fields in an embed, and the server has explicit content filtering turned on, all images are scanned before being shown. What does this mean? If you frequently use embeds for your bot responses, and those embeds include images, you may begin to see high latency on these commands (anywhere from 2 to 10 seconds per embed). If you are concerned about latency for embeded responses, it is recommended you remove all images from your embeds, when possible.`

**Comment by EJH2** [comment]
Done-ish:tm:
